// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sysuser.proto

package server

import (
	"context"

	"go-zero-demo/service/user/rpc/internal/logic"
	"go-zero-demo/service/user/rpc/internal/svc"
	"go-zero-demo/service/user/rpc/userclient"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userclient.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) SysUserAdd(ctx context.Context, in *userclient.SysUserAddReq) (*userclient.CommonResp, error) {
	l := logic.NewSysUserAddLogic(ctx, s.svcCtx)
	return l.SysUserAdd(in)
}

func (s *UserServer) SysUserDelete(ctx context.Context, in *userclient.SysUserDeleteReq) (*userclient.CommonResp, error) {
	l := logic.NewSysUserDeleteLogic(ctx, s.svcCtx)
	return l.SysUserDelete(in)
}

func (s *UserServer) SysUserUpdate(ctx context.Context, in *userclient.SysUserUpdateReq) (*userclient.CommonResp, error) {
	l := logic.NewSysUserUpdateLogic(ctx, s.svcCtx)
	return l.SysUserUpdate(in)
}

func (s *UserServer) SysUserFindOne(ctx context.Context, in *userclient.SysUserFindOneReq) (*userclient.SysUserFindOneResp, error) {
	l := logic.NewSysUserFindOneLogic(ctx, s.svcCtx)
	return l.SysUserFindOne(in)
}

func (s *UserServer) SysUserList(ctx context.Context, in *userclient.SysUserListReq) (*userclient.SysUserListResp, error) {
	l := logic.NewSysUserListLogic(ctx, s.svcCtx)
	return l.SysUserList(in)
}
