// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	sysUser "go-zero-demo/service/user/api/internal/handler/sysUser"
	"go-zero-demo/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/sysUser",
				Handler: sysUser.SysUserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/sysUser",
				Handler: sysUser.SysUserUpHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/sysUser",
				Handler: sysUser.SysUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/sysUser/:id",
				Handler: sysUser.SysUserDelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/sysUserInfo",
				Handler: sysUser.SysUserInfoHandler(serverCtx),
			},
		},
	)
}
