// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type Response struct {
	Code int         `json:"code"` // 业务码
	Msg  string      `json:"msg"`  // 业务信息
	Data interface{} `json:"data"` // 数据
}

type SysUserAddRequest struct {
	Account  string `json:"account,optional"`   // 用户名
	NickName string `json:"nick_name,optional"` // 姓名
	Password string `json:"password,optional"`  // 密码
	State    int64  `json:"state,optional"`     // 状态 1:正常 2:停用 3:封禁
}

type SysUserDelRequest struct {
	Id string `path:"id"` // 用户ID
}

type SysUserInfoRequest struct {
	Id string `form:"id"` // 用户ID
}

type SysUserListRequest struct {
	Current  int64  `form:"current,default=1,optional"`    // 页码
	PageSize int64  `form:"page_size,default=10,optional"` // 页数
	Account  string `form:"account,optional"`              // 用户名
	NickName string `form:"nick_name,optional"`            // 姓名
	Password string `form:"password,optional"`             // 密码
	State    int64  `form:"state,default=99,optional"`     // 状态 1:正常 2:停用 3:封禁
}

type SysUserUpRequest struct {
	Id       string `json:"id"`                 // 用户ID
	Account  string `json:"account,optional"`   // 用户名
	NickName string `json:"nick_name,optional"` // 姓名
	Password string `json:"password,optional"`  // 密码
	State    int64  `json:"state,optional"`     // 状态 1:正常 2:停用 3:封禁
}
